# fly.toml app configuration file generated for sgalalla-geckos on 2026-02-06T15:54:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sgalalla-geckos'
primary_region = 'cdg'

[build]

# [http_service] REMOVED in favor of explicit services
# We expose Port 3000 for BOTH TCP (Signaling/HTTP) and UDP (Game Data)

# TCP Service (Signaling + HTTP)
[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  
  [[services.ports]]
    port = 3000

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
